title: Termeh Mohebbie # your name (or website title) here
logo: "C:\Users\terme\Downloads\Termeh" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Linear Regression Project 
  <br><br>
  I just got some contract work with an Ecommerce company based in New York City that sells clothing online but they also have in-store style and clothing advice sessions. Customers come in to the store, have sessions/meetings with a personal stylist, then they can go home and order either on a mobile app or website for the clothes they want. The company is trying to decide whether to focus their efforts on their mobile app experience or their website. 
  <br><br>
  <a href="https://www.linkedin.com/in/termehmohebbie/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
